// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonAppGestion;

#nullable disable

namespace MonAppGestion.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408091725_AddVersionsTable")]
    partial class AddVersionsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MonAppGestion.Models.Achat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdFournisseur")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumAchat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Versement")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdFournisseur");

                    b.ToTable("Achats");
                });

            modelBuilder.Entity("MonAppGestion.Models.AchatDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AchatId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdAchat");

                    b.Property<decimal>("PrixAchat")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdProduit");

                    b.Property<int>("Qte")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AchatId");

                    b.ToTable("AchatDetails");
                });

            modelBuilder.Entity("MonAppGestion.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("MonAppGestion.Models.Fournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Fournisseurs");
                });

            modelBuilder.Entity("MonAppGestion.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateExpiration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixAchat")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixVente")
                        .HasColumnType("TEXT");

                    b.Property<int>("Qte")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Raccourci")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MonAppGestion.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MonAppGestion.Models.Vente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdClient")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumVente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Versement")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Ventes");
                });

            modelBuilder.Entity("MonAppGestion.Models.VenteDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrixVente")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdProduit");

                    b.Property<int>("Qte")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VenteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdVente");

                    b.HasKey("Id");

                    b.HasIndex("VenteId");

                    b.ToTable("VenteDetails");
                });

            modelBuilder.Entity("MonAppGestion.Models.Version", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("HDD_sn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomBranch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Versions");
                });

            modelBuilder.Entity("MonAppGestion.Models.Achat", b =>
                {
                    b.HasOne("MonAppGestion.Models.Fournisseur", "Fournisseur")
                        .WithMany()
                        .HasForeignKey("IdFournisseur");

                    b.Navigation("Fournisseur");
                });

            modelBuilder.Entity("MonAppGestion.Models.AchatDetail", b =>
                {
                    b.HasOne("MonAppGestion.Models.Achat", null)
                        .WithMany("Details")
                        .HasForeignKey("AchatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MonAppGestion.Models.Vente", b =>
                {
                    b.HasOne("MonAppGestion.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("MonAppGestion.Models.VenteDetail", b =>
                {
                    b.HasOne("MonAppGestion.Models.Vente", null)
                        .WithMany("Details")
                        .HasForeignKey("VenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MonAppGestion.Models.Achat", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("MonAppGestion.Models.Vente", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
